// Code generated by mockery v2.20.0. DO NOT EDIT.

package mocks

import (
	entity "github.com/mateo-tavera/accounting-daily-tasks/entity"
	mock "github.com/stretchr/testify/mock"
)

// RepositoryService is an autogenerated mock type for the RepositoryService type
type RepositoryService struct {
	mock.Mock
}

// CreateTask provides a mock function with given fields: _a0
func (_m *RepositoryService) CreateTask(_a0 entity.Task) (int, error) {
	ret := _m.Called(_a0)

	var r0 int
	var r1 error
	if rf, ok := ret.Get(0).(func(entity.Task) (int, error)); ok {
		return rf(_a0)
	}
	if rf, ok := ret.Get(0).(func(entity.Task) int); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Get(0).(int)
	}

	if rf, ok := ret.Get(1).(func(entity.Task) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DeleteTask provides a mock function with given fields: _a0, _a1
func (_m *RepositoryService) DeleteTask(_a0 int, _a1 string) error {
	ret := _m.Called(_a0, _a1)

	var r0 error
	if rf, ok := ret.Get(0).(func(int, string) error); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetAllTasks provides a mock function with given fields: _a0, _a1
func (_m *RepositoryService) GetAllTasks(_a0 int, _a1 string) ([]entity.Task, error) {
	ret := _m.Called(_a0, _a1)

	var r0 []entity.Task
	var r1 error
	if rf, ok := ret.Get(0).(func(int, string) ([]entity.Task, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(int, string) []entity.Task); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.Task)
		}
	}

	if rf, ok := ret.Get(1).(func(int, string) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetTask provides a mock function with given fields: _a0, _a1
func (_m *RepositoryService) GetTask(_a0 int, _a1 string) (*entity.Task, error) {
	ret := _m.Called(_a0, _a1)

	var r0 *entity.Task
	var r1 error
	if rf, ok := ret.Get(0).(func(int, string) (*entity.Task, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(int, string) *entity.Task); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Task)
		}
	}

	if rf, ok := ret.Get(1).(func(int, string) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateTask provides a mock function with given fields: _a0
func (_m *RepositoryService) UpdateTask(_a0 entity.Task) error {
	ret := _m.Called(_a0)

	var r0 error
	if rf, ok := ret.Get(0).(func(entity.Task) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

type mockConstructorTestingTNewRepositoryService interface {
	mock.TestingT
	Cleanup(func())
}

// NewRepositoryService creates a new instance of RepositoryService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewRepositoryService(t mockConstructorTestingTNewRepositoryService) *RepositoryService {
	mock := &RepositoryService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
